services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - WATCHFILES_FORCE_POLLING=1
      - PYTHONPATH=/
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri 'sqlite:///var/mlflow.db'
    volumes:
      - ./mlartifacts:/var/mlartifacts
      - ./mlflow.db:/var/mlflow.db
    ports:
      - "5000:5000"
    restart: always