services:
  app:
    build: .
    ports:
      - "8000:8000"
  # mlflow:
  #   image: ghcr.io/mlflow/mlflow:latest
  #   command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri 'sqlite:///mlflow/mlflow.db'
  #   volumes:
  #     - ./mlflow.db:/mlflow/mlflow.db
  #   ports:
  #     - "5000:5000"